name = "Phase Coffee Factory"
author = "Neeyo"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b46a6dbc6d85d21e9f1556a2317a88bc6ec9033d725f0b9aa74e7a505a86100e"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
