name = "Phase Coffee Factory"
author = "Neeyo"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c75b0755e04035e3a83c726ce53f708e3fe503908081c5d048cf3a88423dfab1"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
