name = "Phase Coffee Factory"
author = "Neeyo"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a25b1227d44687f246a4d3623d0f297de78432d5d9f2dc4bd4a4c053370c5b7"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
