
["Common Configs for Kawaii Dishes"]
	#Define if the Kawaii Effect can send messages to local players
	canSendMessage = false
	#Set the chance to message the player
	#Range: 0.0 ~ 1.0
	chanceToMessage = 1.5E-4
	#Sets the messages that are sent to the player
	messages = ["What the helly are you wearing?", "You look nice today", "Jelly was so cute today !", "Hey babe, lookin' for a good time?"]
	#Should the mobs spawn with the maid dresses
	shouldSpawn = true
	#Sets the chance for mobs to spawn with maid dresses
	#Range: 0.0 ~ 1.0
	chanceToSpawn = 0.025
	#Sets the chance for mobs that spawn with maid dresses to drop them
	#Range: 0.0 ~ 1.0
	chanceToDrop = 0.35
	#Should the add item trades for villagers
	villagerTrades = true
	#Should the add item trades for wandering traders
	wanderingTraderTrades = true
	#Structure generation weights for the village houses
	#Range: 0 ~ 450
	villageStructWeight = 125

